import type { Metadata } from "next";
import Template from "@/components/Template";
import { SessionProvider } from "next-auth/react";
import Variant from "@/context/Variant";
import "./globals.css";

export const metadata: Metadata = {
  title: "PlatChasers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Variant>
            <Template>{children}</Template>
          </Variant>
        </SessionProvider>
      </body>
    </html>
  );
}
